// Code generated by protoc-gen-go-http. DO NOT EDIT.

package domain

import (
	http "github.com/ducketlab/mingo/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path: "/auth.domain.DomainService/CreateDomain",
			},
			{
				Path: "/auth.domain.DomainService/DescribeDomain",
			},
			{
				Path: "/auth.domain.DomainService/QueryDomain",
			},
			{
				Path: "/auth.domain.DomainService/DeleteDomain",
			},
		},
	}
	return set
}
