// Code generated by protoc-gen-go-http. DO NOT EDIT.

package token

import (
	http "github.com/ducketlab/mingo/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path: "/auth.token.TokenService/ValidateToken",
			},
			{
				Path: "/auth.token.TokenService/DescribeToken",
			},
		},
	}
	return set
}
