// Code generated by protoc-gen-go-http. DO NOT EDIT.

package permission

import (
	http "github.com/ducketlab/mingo/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path: "/auth.permission.PermissionService/QueryPermission",
			},
			{
				Path: "/auth.permission.PermissionService/QueryRole",
			},
			{
				Path: "/auth.permission.PermissionService/CheckPermission",
			},
		},
	}
	return set
}
