// Code generated by protoc-gen-go-http. DO NOT EDIT.

package namespace

import (
	http "github.com/ducketlab/mingo/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path: "/auth.namespace.NamespaceService/CreateNamespace",
			},
			{
				Path: "/auth.namespace.NamespaceService/QueryNamespace",
			},
			{
				Path: "/auth.namespace.NamespaceService/DescribeNamespace",
			},
			{
				Path: "/auth.namespace.NamespaceService/DeleteNamespace",
			},
		},
	}
	return set
}
