// Code generated by protoc-gen-go-http. DO NOT EDIT.

package user

import (
	http "github.com/ducketlab/mingo/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path: "/auth.user.UserService/QueryAccount",
			},
			{
				Path: "/auth.user.UserService/DescribeAccount",
			},
			{
				Path: "/auth.user.UserService/CreateAccount",
			},
		},
	}
	return set
}
