// Code generated by protoc-gen-go-http. DO NOT EDIT.

package micro

import (
	http "github.com/ducketlab/mingo/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path: "/auth.micro.MicroService/ValidateClientCredential",
			},
			{
				Path: "/auth.micro.MicroService/CreateService",
			},
			{
				Path: "/auth.micro.MicroService/QueryService",
			},
			{
				Path: "/auth.micro.MicroService/DescribeService",
			},
			{
				Path: "/auth.micro.MicroService/DeleteService",
			},
			{
				Path: "/auth.micro.MicroService/RefreshServiceClientSecret",
			},
		},
	}
	return set
}
