// Code generated by protoc-gen-go-http. DO NOT EDIT.

package policy

import (
	http "github.com/ducketlab/mingo/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path: "/auth.policy.PolicyService/CreatePolicy",
			},
			{
				Path: "/auth.policy.PolicyService/DescribePolicy",
			},
			{
				Path: "/auth.policy.PolicyService/DeletePolicy",
			},
		},
	}
	return set
}
